### ISSUE TITLE
R 3.4.0 needed?

### ISSUE THREAD

**Issue by gaborcsardi** [dirkschumacher/rpicosat#4]
Nice project! Do you think the R >= 3.4.0 dependency could be relaxed?

**Comment by dirkschumacher** [comment]
Yes it can be relaxed. What version would you require? >= 3.3?

**Comment by gaborcsardi** [comment]
`>= 3.1.x` ideally. Do you need to modify anything for that? Or just test?

**Comment by dirkschumacher** [comment]
I think we just need to test it.
